### ISSUE TITLE
"D1" and "D2"

### ISSUE THREAD

**Issue by mjuddi** [napyk/trigorilla-pro#2]
Hey napyk, thanks for your efforts! this is pretty much the only place to find any info on this board.

Do you know what it means if "D1" and "D2" are lighted up on the board?

When I turn the printer on I get no sound from the buzzer and nothing on the touch screen either. The only thing lighted up on the board are these two lights.

Do you think it's bricked or do you think it can be revived somehow?

Haven't touched the bootloader at all yet, but I accidentally turned the printer on with an SD card inside with firmware (from Anycubic) and I got a few beeps and this happened. Feel like something must've happened with the bootloader because of this.

Thanks again!

**Comment by p1ngb4ck** [comment]
Try to flash the bootloader as described in this repo here, and afterwards try to flash the ac firmware via the new bootloader..

**Comment by Blue-Beaker** [comment]
> Try to flash the bootloader as described in this repo here, and afterwards try to flash the ac firmware via the new bootloader..

I've flashed bootloader into my printer with stm32cubeprogrammer. How to flash firmware via bootloader? and which firmware should I use? I put sd card with update.zw into the printer and power up with usb, D1 just keeps flashing.

**Comment by mjuddi** [comment]
https://www.st.com/en/development-tools/flasher-stm32.html (Firmware flash program)
https://marlinfw.org/docs/basics/install_platformio_vscode.html (Set up VSCode + PlatformIO to compile firmware)
https://github.com/SXHXC/Marlin-Anycubic-Predator-Trigorilla-PRO (Firmware + good documentation on the process)

Here is a good video as well:
https://www.youtube.com/watch?v=g2cAJXle6t0
